### ISSUE TITLE
Proper functionality of pause and resume ?

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [ronz94/Steadfast#9]
Found around this commit: 8fbca52c62f63bc771f1dcd1bfc8bf8b7f11e6c3
Pause button doesn't seem to work properly (more testing is required), also , there is no option to resume the download once it is paused. Someone please confirm whether pause button really pauses the downloads or not as I don't have much bandwidth to test it on long downloads. Also if it does work where could one would resume the download after it has been paused ?

**Comment by Mr-Kumar-Abhishek** [comment]
So.. I have looked in the issue and also tested the pause functionality. The problem is caused because the download is executed in EDT (event dispatcher thread). Rather it should be executed in any background thread. Execution in EDT leaves GUI unresponsive (so pause button doesn't works during a download) .Also use of background thread will also will change how the pause button works. Any ideas how to approach this ?

**Comment by ronz94** [comment]
I have checked it out. Execution in EDT is hampering the progress bar and not the start and cancel buttons. This is so,because the progress bar successfully shows the progress once the download is paused,but it is not showing the progress while the download is in process. So,we now have to resolve the issue for the progress bar.

**Comment by Mr-Kumar-Abhishek** [comment]
Thanks for testing it out, I had a lot of trouble testing it properly as I had low bandwidth.
